### ISSUE TITLE
lack of tf-idf-input.json

### ISSUE THREAD

**Issue by Zongyang-Li** [wenhuchen/OTT-QA#2]
Hello, in the process of trying to build the corpus, I found that a file was missing, which caused the program to fail to run normally.

Command code：
python build_tfidf.py --build_option text_title --out_dir text_title_bm25 --option bm25

FileNotFoundError:
 [Errno 2] No such file or directory: '/tmp/tf-idf-input.json'

Then, I searched the entire folder but did not find the file. Hope you fix this error or provide the exact location of the file.
Thanks for your work.

**Comment by wenhuchen** [comment]
The script is supposed to write to /tmp/tf-idf-input.json, not reading from it. I'm afraid your computer doesn't have /tmp/ folder, which might cause this problem to occur? I would suggest you add --tmp_file [FILE_NAME] argument to the command to address it.
