### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Yaxuan-Z** [wenhuchen/OTT-QA#3]
Sorry to  bother you but when I run the code in 

Step1-2: Build inedx for retriever
cd retriever/
python build_tfidf.py --build_option text_title --out_dir text_title_bm25 --option bm25
python build_tfidf.py --build_option title_sectitle_schema --out_dir title_sectitle_schema

It create the folder text_title_bm25 and  title_sectitle_schema but have nothing in it and There are TypeErrors: TypeError: 'NoneType' object is not subscriptable

**Comment by wenhuchen** [comment]
Please list the whole error log. I have no idea which line reports this error.

**Comment by Yaxuan-Z** [comment]
(base) yaxuandeMacBook-Pro:~ yaxuanzhang$ cd /Users/yaxuanzhang/Downloads/OTT-QA-master/retriever 
(base) yaxuandeMacBook-Pro:retriever yaxuanzhang$ python build_tfidf.py --build_option text_title --out_dir text_title_bm25 --option bm25
03/25/2021 03:27:14 PM: [ Building corpus... ]
03/25/2021 03:29:59 PM: [ Building DB file... ]
03/25/2021 03:29:59 PM: [ Reading into database... ]
1it [01:37, 97.44s/it]████████████████████████████| 1/1 [01:37<00:00, 97.44s/it]
100%|█████████████████████████████████████████████| 1/1 [01:37<00:00, 97.45s/it]
03/25/2021 03:31:37 PM: [ Read 6057029 docs. ]
03/25/2021 03:31:37 PM: [ Committing... ]
03/25/2021 03:31:39 PM: [ Counting words... ]
03/25/2021 03:31:46 PM: [ Mapping... ]
03/25/2021 03:31:46 PM: [ -------------------------Batch 1/11------------------------- ]
multiprocessing.pool.RemoteTraceback: 
"""
Traceback (most recent call last):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 125, in worker
    result = (True, func(*args, **kwds))
  File "/Users/yaxuanzhang/Downloads/OTT-QA-master/retriever/build_tfidf.py", line 257, in count
    col.extend([DOC2IDX[doc_id]] * len(counts))
TypeError: 'NoneType' object is not subscriptable
"""

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "build_tfidf.py", line 401, in <module>
    count_matrix, doc_dict = get_count_matrix(
  File "build_tfidf.py", line 290, in get_count_matrix
    for b_row, b_col, b_data in workers.imap_unordered(_count, batch):
  File "/opt/anaconda3/lib/python3.8/multiprocessing/pool.py", line 868, in next
    raise value
TypeError: 'NoneType' object is not subscriptable

**Comment by wenhuchen** [comment]
I reran my code and it works just fine on my computer, I think DOC2IDX is somehow invalid in your code, maybe caused by some errors in the previous steps. My code is largely based on https://github.com/facebookresearch/DrQA/tree/master/drqa/retriever, I'm not a hundred percent sure of all the details. I guess maybe the library or something is mismatched, for example, like pexpect, etc.

**Comment by Yaxuan-Z** [comment]
Thanks of your reply, I’m  checking the code and find that we didn’t install the DrQA package and import some other files. The code now uses the default settings on your computer, so other partners in our group get the error that the tmp file does not exist. We need to import the file according to the code by ourselves.  Thank you again for your help~

**Comment by yitong-jia** [comment]
Hi, for step 2-2, when i run the first command, it took the really long time on iteration, and i just stop it, and yesterday, when i do the step2-2 again, it showed that the problem i never had before, could you please help me to fix it.
<img width="1009" alt="屏幕快照 2021-04-08 下午12 59 50" src="https://user-images.githubusercontent.com/82135571/113972257-ee7d2180-986c-11eb-9815-01c59950a49c.png">
<img width="1555" alt="屏幕快照 2021-04-02 下午5 40 42" src="https://user-images.githubusercontent.com/82135571/113972362-12d8fe00-986d-11eb-8f4a-a66819637476.png">
