### ISSUE TITLE
Step2-2

### ISSUE THREAD

**Issue by yitong-jia** [wenhuchen/OTT-QA#4]
Hi，before 
<img width="1555" alt="屏幕快照 2021-04-02 下午5 40 42" src="https://user-images.githubusercontent.com/82135571/113986049-648a8400-987f-11eb-8363-32abf462bb06.png">
i run the step 2-2, it took a really long time in iteration, so i stopped it. but yesterday, i run it again, it shows many errors. I want to know the reason.
And could you please tell us how to change the dataset to the hotpotqa.
<img width="1009" alt="屏幕快照 2021-04-08 下午12 59 50" src="https://user-images.githubusercontent.com/82135571/113985943-46248880-987f-11eb-9bb1-c1851b7ff9fe.png">

**Comment by wenhuchen** [comment]
Sorry for the late reply, just added https://github.com/wenhuchen/OTT-QA/blob/ed6c36f1e325e8726debf7fd12c6b3e1b92cb697/train_stage12.py#L75 to solve the problem.

**Comment by yitong-jia** [comment]
Thank you~
