### ISSUE TITLE
Step3-1: Loss of test.json

### ISSUE THREAD

**Issue by chirain1206** [wenhuchen/OTT-QA#7]
Hi wenhu,
when I execute the last command in Step 3-1: "python retrieve_and_preprocess.py --split test_retrieve --model retriever/title_sectitle_schema/index-tfidf-ngram\=2-hash\=16777216-tokenizer\=simple.npz", it returned that "released_data/test.json" is not found. I read over codes but I didn't find which command is responsible for producing this file. Also, I skipped training process in step 2 and download the model instead. Is this the possible reason?

![File not found](https://user-images.githubusercontent.com/37463897/119278687-cc5d1a00-bbf4-11eb-966c-a4be00648fdc.png)

**Comment by wenhuchen** [comment]
The test data is blind, you need to use https://github.com/wenhuchen/OTT-QA/blob/master/released_data/test.blind.json, which does not contain the answer (you need to submit your result to codalab to evaluate your model). 

If you just want to play around with the code, I suggest you use dev data.
