### ISSUE TITLE
Wikipedia HTMLs 

### ISSUE THREAD

**Issue by Mayer123** [wenhuchen/OTT-QA#8]
Thanks for sharing the code and data! I'm wondering which version of Wikipedia dump did you use? Also, how did you get the HTML files from the original Wikipedia dump, e.g. did you use any specific tool to convert XML to HTML?

**Comment by wenhuchen** [comment]
I didn't use the Wikipedia Dump from the WikiMedia website, instead, I directly sent html request to Wikipedia servers to download the HTML files for all the pages. My preprocessing was done directly on top of HTML using the python html parsing library. The process was conducted in July 2021, so the Wikipedia pages are mostly coming from that time.
